# -*- coding: utf-8 -*-
"""Big_Data_Project_Healthcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbE9kyijyFuQWzjq590YbzhsqgGFayzx
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col,sum,when

# Step 1: Create SparkSession
spark = SparkSession.builder \
.appName("BigDataInHealthcare") \
.getOrCreate()

# Step 2: Load CSV
df = spark.read.csv("/content/healthcare_dataset.csv", header=True, inferSchema=True)

# Step 3: Show schema and sample rows
df.printSchema()
df.show()

print(df.columns)

df.count()

duplicates=df.count()-df.dropDuplicates().count()
print(duplicates)

from pyspark.sql.functions import datediff

# Calculate the number of missing values, outliers, and duplicates
total_cells = df.count() * len(df.columns)
total_missing = df.select([sum(col(c).isNull().cast("int")).alias(c) for c in df.columns]).collect()[0][0]

# Calculate Stay Duration before checking for outliers
df = df.withColumn("Stay Duration", datediff(col("Discharge Date"), col("Date of Admission")))

total_outliers = df.filter((col("Age") < 0) | (col("Age") > 120)).count() + df.filter(col("Billing Amount").isNull()).count() + df.filter((col("Stay Duration") <= 0) | (col("Stay Duration") > 365)).count()

# Calculate the data quality score
total_anomalies = total_missing + total_outliers + duplicates
data_quality_score = ((total_cells - total_anomalies) / total_cells) * 100

# Print the data quality score
print(f"Data Quality Score: {data_quality_score:.2f}%")

#Check Null Values
df.select([sum(col(c).isNull().cast("int")).alias(c) for c in df.columns]).show()

# Standardize Text columns
from pyspark.sql.functions import initcap,trim,upper,lower,to_date,avg,min,max
df=df.withColumn("Name",initcap(trim(col("Name"))))\
 .withColumn("Gender",upper(trim(col("Gender")))) \
 .withColumn("BloodType",upper(trim(col("Blood Type")))) \
 .withColumn("Hospital",initcap(trim(col("Hospital")))) \
 .withColumn("Date of Admission",to_date(col("Date of Admission"),"yyyy-MM-dd")) \
 .withColumn("Discharge Date",to_date(col("Discharge Date"),"yyyy-MM-dd"))
df.show()

#Data Cleaning
dup=df.groupBy("Name","Date of Admission","Hospital").count().filter("count>1")
dup.show()
df=df.dropDuplicates()

df.count()

#finding invalid admission
df.filter(col("Discharge Date").isNotNull()&(col("Discharge Date")<col("Date of Admission"))).show()

#Data Aggregation - Patients counts by Hospitals & Admission Type
df.groupBy("Hospital").count().orderBy(col("count").desc()).show()
df.groupBy("Admission Type").count().show()

#Average Billing by Hospital &  Medication
df.createOrReplaceTempView("Healthcare_Sql")

query1="""
SELECT Hospital, AVG(`Billing Amount`) AS Avg_Billing
FROM Healthcare_Sql
GROUP BY Hospital
ORDER BY Avg_Billing DESC
"""
query2="""
SELECT Medication, AVG(`Billing Amount`) AS Avg_Billing
FROM Healthcare_Sql
GROUP BY Medication
ORDER BY Avg_Billing DESC
"""
print("Average Billing by Hospital:")
spark.sql(query1).show()
print("Average Billing by Medication:")
spark.sql(query2).show()

#Patients counts per Medical condition & Gender
query3="""
SELECT `Medical Condition`, Gender, COUNT
FROM(
  SELECT `Medical Condition`, Gender, COUNT(*) AS COUNT, ROW_NUMBER() OVER (PARTITION BY `Medical Condition` ORDER BY COUNT(*) DESC)AS rank
  FROM Healthcare_Sql
  GROUP BY `Medical Condition`, Gender
)
"""
print("Patients counts per Medical Condition & Gender:")
spark.sql(query3).show()

#Hospital with Highest Patients counts
query4="""
SELECT Hospital, COUNT(*) AS Patients_Count
FROM Healthcare_Sql
GROUP BY Hospital
ORDER BY Patients_Count DESC
LIMIT 10
"""
print("Hospital with Highest Patients counts:")
spark.sql(query4).show()

#Most Common Medical Conditions & Age distribution by Medical Condition
df.groupBy("Medical Condition").count().orderBy(col("count").desc()).show()
df.groupBy("Medical Condition").agg(avg("Age").alias("Average Age"),min("Age").alias("Minimum Age"),max("Age").alias("Maximum Age")).show()

#Average treatment cost per medical condition
df.groupBy("Medical Condition").agg(avg("Billing Amount").alias("Average Treatment Cost")).show()

#Patients counts per Test results category
df.groupBy("Test Results").count().orderBy("count").show()

#Summary statistics for validation
df.describe(["Age","Billing Amount"]).show()

#Negative Cost Fixing
#As we found a negative value in Min Of Billing Amount....We need to check it either it is an error or Insurance refund/claim.....
insurance_refunds=df.filter((col("Billing Amount")<0)&(col("Insurance Provider").isNotNull()))
insurance_refunds.show()

invalid_costs=df.filter((col("Billing Amount")<0)&(col("Insurance Provider").isNull()))
invalid_costs.show()

#Found Insurance refunds....so Label them as Normal Charges and Insurance Providers...
df=df.withColumn("CostType",when((col("Billing Amount")<0)&(col("Insurance Provider").isNotNull()),"Insurance Refund").otherwise("Normal Charge"))

#Replace with mean of Valid costs to  Handle Negative values...
avg_billing=df.filter(col("Billing Amount")>=0).agg(avg("Billing Amount")).first()[0]

df=df.withColumn("Billing Amount",when(col("Billing Amount")<0,avg_billing).otherwise(col("Billing Amount")))
df.show(5)

df.filter(col("Billing Amount")<0).count()

df.describe(["Billing Amount"]).show()

# Calculate the number of missing values, outliers, and duplicates
total_cells = df.count() * len(df.columns)
total_missing = df.select([sum(col(c).isNull().cast("int")).alias(c) for c in df.columns]).collect()[0][0]

total_outliers = df.filter((col("Age") < 0) | (col("Age") > 120)).count() + df.filter(col("Billing Amount").isNull()).count() + df.filter((col("Stay Duration") <= 0) | (col("Stay Duration") > 365)).count()
duplicates = df.count() - df.dropDuplicates().count()

# Calculate the data quality score
total_anomalies = total_missing + total_outliers + duplicates
data_quality_score = ((total_cells - total_anomalies) / total_cells) * 100

# Print the data quality score
print(f"Data Quality Score: {data_quality_score:.2f}%")